agent_params_loader:
  ros__parameters:
    # GLOBAL PARAMETERS
    sampling_time: 0.001
    runge_kutta_45: True
    robot_name: "pioneer3at"
    laser_sensor_name: "laser"
    robot_initial_orientation: -90.0
    robot_waypoints: [0.0,-6.0,0.0,6.0]
    robot_initial_position: [0.0,6.0]
    robot_radius: 0.3
    robot_mass: 35
    robot_goal_weight: 2.0
    robot_obstacle_weight: 10.0
    robot_social_weight: 15.0
    robot_velocity: 1.0
    robot_ignore_obstacles: ["circular_workspace"]
    agents: ["agent1","agent2","agent3","agent4","agent5","agent6","agent7"] 
    # ACTORS PARAMETERS
    agent1:
      waypoints: [-4.2,-4.2,4.2,4.2] 
      initial_orientation: -135.0 
      initial_position: [4.2,4.2] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent2:
      waypoints: [-6.0,0.0,6.0,0.0] 
      initial_orientation: -180.0 
      initial_position: [6.0,0.0] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent3:
      waypoints: [-4.2,4.2,4.2,-4.2] 
      initial_orientation: 135.0 
      initial_position: [4.2,-4.2] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent4:
      waypoints: [0.0,6.0,0.0,-6.0] 
      initial_orientation: 90.0 
      initial_position: [0.0,-6.0] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent5:
      waypoints: [4.2,4.2,-4.2,-4.2] 
      initial_orientation: 45.0 
      initial_position: [-4.2,-4.2]
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent6:
      waypoints: [6.0,0.0,-6.0,0.0] 
      initial_orientation: 0.0 
      initial_position: [-6.0,0.0] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False
    agent7:
      waypoints: [4.2,-4.2,-4.2,4.2] 
      initial_orientation: -45.0 
      initial_position: [-4.2,4.2] 
      radius: 0.3
      mass: 75
      goal_weight: 2.0
      obstacle_weight: 10.0
      social_weight: 15.0
      group_gaze_weight: 0.0
      group_coh_weight: 0.0
      group_rep_weight: 0.0
      velocity: 0.9
      animation_factor: 5.1
      animation_name: "walking"
      people_distance: 6.0
      ignore_obstacles: ["circular_workspace"]
      publish_forces: False